---
name: Install dependencies
description: |
  Use pip to install all dependencies
  listed under requirements.txt.
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
