# Note: DO terraform apply after updating templates, renaming things.

# Generate config YAML to provide values for CI env:
resource "local_file" "locally_generated_config_yaml" {
  filename = "../config.yml"
  content  = <<-EOT
    ---
    # Do not edit this file. It is managed by Terraform.
    # DO terraform apply after renaming things.
    # Python:
    py_version: ${local.python_version_entire_project}
    core_py: ${local.local_python_core_script_name}
    core_folder: ${local.local_core_folder_name}
    skip_pylint: ${var.ci_python_skip_code_quality_option}
    skip_pytest: ${var.ci_python_skip_testing_option}
    coverage: ${var.ci_python_unit_testing_code_coverage_value}
    core_path: ${local.local_python_core_script_path}
    # Web:
    nodejs_version: ${var.ci_nodejs_version}
    # Cloud:
    region: ${local.cloud_selected_region}
    cloud_folder: ${local.local_cloud_folder_name}
    # S3:
    scripts_bucket: ${local.s3_bucket_scripts_name}
    # Lambda:
    core_zip_dir: ${local.ci_lambda_deploy_main_temp_zip_dir_name}
    core_zipfile: ${local.ci_lambda_deploy_main_temp_zip_file_name}
    core_function: ${local.lambda_function_mappings["core"].name}
    list_zipfile: ${local.ci_lambda_deploy_list_temp_zip_file_name}
    list_src: ${local.local_lambda_list_src_python_code_path}
    list_function: ${local.lambda_function_mappings["list"].name}
    cleanup_zip_dir: ${local.ci_lambda_deploy_cleanup_temp_zip_dir_name}
    cleanup_zipfile: ${local.ci_lambda_deploy_cleanup_temp_zip_file_name}
    cleanup_src: ${local.local_lambda_cleanup_src_python_code_path}
    cleanup_function: ${local.lambda_function_mappings["cleanup"].name}
    upload_zip_dir: ${local.ci_lambda_deploy_upload_temp_zip_dir_name}
    upload_zipfile: ${local.ci_lambda_deploy_upload_temp_zip_file_name}
    upload_src: ${local.local_lambda_upload_src_python_code_path}
    upload_function: ${local.lambda_function_mappings["upload"].name}
    # Bash:
    verify: ${local.local_verify_s3_deploy_aux_bash_script_path}
    # CloudFront:
    distribution: ${var.cloudfront_distribution_id}
  EOT
}


# Web:

# Generate main page index HTML from template:
resource "local_file" "locally_generated_html_documents" {
  for_each = local.html_template_mappings

  filename = each.value.local_document_path
  content = <<-EOT
    <!-- Do not edit this file. It is managed by Terraform. -->
    <!-- DO terraform apply after updating the template. -->
    ${templatefile("/${each.value.local_src_template_path}", {
  bucket                = local.s3_bucket_scripts_name
  core                  = local.local_python_core_script_name
  version               = local.js_template_mappings["version"].remote_js_target_path
  list                  = local.js_template_mappings["list"].remote_js_target_path
  upload                = local.js_template_mappings["upload"].remote_js_target_path
  generate              = local.js_template_mappings["generate"].remote_js_target_path
  tabs                  = local.remote_js_tabs_target_path
  install_ffmpeg        = local.html_install_ffmpeg_text
  install_vlc           = local.html_install_vlc_text
  download_music_videos = local.html_download_music_videos_contact_text
  css                   = "${local.local_css_subfolder_name}/styles.css"
})}
  EOT
}

# Generate JavaScripts from templates:
resource "local_file" "locally_generated_javascripts" {
  for_each = local.js_template_mappings

  filename = each.value.local_script_path
  content = <<-EOT
    // Do not edit this file. It is managed by Terraform.
    // DO terraform apply after updating templates, renaming things.
    ${templatefile(each.value.local_src_template_path,
  merge(
    local.js_template_vars,
    { path = each.value.apigw_route_value }
  )
)}
  EOT
}
