# Note: DO terraform apply after updating templates, renaming things.

# Generate config YAML to provide values for CI env:
resource "local_file" "locally-generated-config-yaml" {
  filename = "../config.yml"
  content  = <<-EOT
    # Do not edit this file. It is managed by Terraform.
    # DO terraform apply after renaming things.
    # Python:
    python_version: ${local.python_version_entire_project}
    core_py_name: ${var.local-python-core-script-name}
    core_subfolder: ${var.local-core-folder-name}
    skip_python_code_quality: ${var.ci-python-skip-code-quality-option}
    skip_testing: ${var.ci-python-skip-testing-option}
    unit_testing_target_code_coverage: ${var.ci-python-unit-testing-code-coverage-option}
    core_py_path: ${local.python_core_script_local_path}
    # Web:
    nodejs_version: ${var.ci-nodejs-version}
    # Cloud:
    aws_project_region: ${local.aws_selected_region}
    cloud_folder: ${var.local-cloud-folder-name}
    # S3:
    scripts_bucket_name: ${var.s3-scripts-bucket-name}
    # Lambda:
    core_zip_dir_name: ${var.ci-lambda-main-temp-zip-dir-name}
    core_zip_file_name: ${var.ci-lambda-main-temp-zip-file-name}
    core_function_name: ${var.lambda-core-function-name}
    list_zip_file_nam: ${var.ci-lambda-list-temp-zip-file-name}
    list_code_src_path: ${local.list_python_code_src_local_path}
    list_function_name: ${var.lambda-list-function-name}
    cleanup_zip_dir_name: ${var.ci-lambda-cleanup-temp-zip-dir-name}
    cleanup_zip_file_name: ${var.ci-lambda-cleanup-temp-zip-file-name}
    cleanup_code_src_path: ${local.cleanup_python_code_src_local_path}
    cleanup_function_name: ${var.lambda-cleanup-function-name}
    upload_zip_dir_name: ${var.ci-lambda-upload-temp-zip-dir-name}
    upload_zip_file_name: ${var.ci-lambda-upload-temp-zip-file-name}
    upload_code_src_path: ${local.upload_python_code_src_local_path}
    upload_function_name: ${var.lambda-upload-function-name}
    # Bash:
    verify_s3_deploy_aux_path: ${var.local-bash-aux-script-verify-s3-deploy-path}
    # CloudFront:
    cloudfront_distribution_id: ${var.cloudfront-distribution-id}
  EOT
}


# Web:

# Generate main page index HTML from template:
resource "local_file" "locally-generated-index-html-document" {
  filename = "../${var.local-cloud-folder-name}/index.html"
  content = <<-EOT
    <!-- Do not edit this file. It is managed by Terraform. -->
    <!-- DO terraform apply after updating the template. -->
    ${templatefile("../${local.html_index_template_path}", {
  bucket                = var.s3-scripts-bucket-name
  core                  = var.local-python-core-script-name
  version               = local.js_files.version-js.target_web_path
  list                  = local.js_files.list-js.target_web_path
  upload                = local.js_files.upload-js.target_web_path
  tabs                  = local.tabs_target_web_path
  install_ffmpeg        = local.text_install_ffmpeg
  install_vlc           = local.text_install_vlc
  download_music_videos = local.text_download_music_videos_contact
})}
  EOT
}

# Generate JavaScripts from templates:
resource "local_file" "locally-generated-js-scripts" {
  for_each = local.js_files

  filename = each.value.script_name
  content = <<-EOT
    // Do not edit this file. It is managed by Terraform.
    // DO terraform apply after updating templates, renaming things.
    ${templatefile(each.value.src_template,
  merge(
    local.js_template_vars,
    { path = each.value.path }
  )
)}
  EOT
}
